### ISSUE TITLE
Dockerless version

### ISSUE THREAD

**Issue by matejdro** [sett-and-hive/sarif-to-comment-action#256]
### Describe the Feature Request

This action currently runs in a docker only, which makes it difficult to use on self-hosted runners.

### Describe the Use Case

When self hosted runners is running in a Docker container itself, it does not support nested docker actions, which means that this action cannot be used

### Describe Preferred Solution

In addition do Docker variant, also include composite action variant (for example, like here: https://github.com/EnricoMi/publish-unit-test-result-action#running-as-a-composite-action)

**Comment by tomwillis608** [comment]
Merge the pull request from @matejdro
